In [2]:
import numpy as np

In [8]:
#Cria uma matriz unidimancional

mt1 = np.array([12, 34, 26, 10, 10])
print(mt)
print(type(mt))

[12 34 26 10 10]
<class 'numpy.ndarray'>


In [14]:
#Cria um array com um tipo específico de dados
#Cria um array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([2, 3, 4], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[2 3 4]
<class 'numpy.ndarray'>


In [18]:
#Mudar o tipo do array
mt = np.array([2.1, 3.1, 4.5, 5.6])
print(mt)
mtInt = mt.astype(np.int32)
print(mtInt)

[2.1 3.1 4.5 5.6]
[2 3 4 5]


In [21]:
#Fazendo o inverso da conversão
mtInverse = mt.astype(float)
print(mtInverse)

[2.1 3.1 4.5 5.6]


In [23]:
#Matriz com mais de uma dimansão
#Cria uma matriz bidimencional
mt2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(mt2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
#Cria arrays vazios tipificados
# 'empty' significa que não são inicializados, não que são vazios.
vazio = np.empty([1, 2, 3], dtype = int)
print(vazio)
print("-----------")
#Cria uma matriz 4x3 com valores zeros
matriz4x3 = np.zeros([4,3])
print(matriz4x3)
print("-----------")
#Cria uma matriz 5x7 com valores iguais a 1
um = np.ones([5,7])
print(um)
print("-----------")
#Cria uma matriz com valoras da diagonal iguais a 1
diagonal = np.eye(5)
print(diagonal)
print("-----------")

[[[         0 1072693248          0]
  [1073741824          0 1074266112]]]
-----------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-----------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-----------


In [41]:
#Valores aleatórios entre um e zero
aleatorio = np.random.random(5)
print(aleatorio)
print("-----------")
#Valores aleatórios distr. normal contendo negativos
aleatorio = np.random.randn(5)
print(aleatorio)
print("-----------")
#Valores aleatórios 3 x 4
aleatorio = (10*np.random.random((3, 4)))
print(aleatorio)
print("-----------")

[0.34355661 0.02818364 0.83393979 0.64685225 0.63191356]
-----------
[-1.52969873  0.3299761   0.46800615 -0.09087062 -0.20117174]
-----------
[[0.27202869 4.46628141 7.98589977 8.96395484]
 [7.57906461 4.54126141 5.8825242  3.81115189]
 [7.08627838 7.48946338 3.32753655 9.89748062]]
-----------


In [47]:
#Outra forma de gerar aleatorios
#Uso de semente
gnr = np.random.default_rng(1)
ale = gnr.random(3)
print(ale)
print("-----------")
#Gerar inteiros
ale = gnr.integers(10, size=(3, 4))
print(ale)

[0.51182162 0.9504637  0.14415961]
-----------
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [51]:
#UNIQUE -> Remove repetições
j = np.array([11, 12, 2, 4, 11, 55, 2, 15])
print(j)
j = np.unique(j)
print(j)

[11 12  2  4 11 55  2 15]
[ 2  4 11 12 15 55]


In [55]:
#Funções específicas
#Cria uma matriz bidimencional k

k = np.array([[17, 22, 43], [27, 25, 14], [15, 24, 32]])
print(k)

#Mostra um elemento específico da matriz k
print(k[0][1])

#Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [61]:
#Funções matemáticas
#Mostra o maior valor da matriz k
print(k.max())
#Mostra o menor valor da matriz k
print(k.min())
#Mostra a soma dos valores da matriz k
print(k.sum())
#Mostra o valor da média dos valores da matriz k
print(k.mean())
#Mostra o valor do desvio padrão (standard deviation) dos valores da matriz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [64]:
#Funções universais, aplicadas a todos os elementos
#Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

#Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [69]:
#Extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
#Mostra elementos na posição 2
print(m[1])
print("-----------")
#Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-----------")
#Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])
print("-----------")
#Mostra o array criado a partir da antepenultima
#posição até o final
print(m[-3:])

2
-----------
[1 2]
-----------
[2 3 4 5 6]
-----------
[4 5 6]


In [76]:
#Extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("-----------")
#Primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("-----------")
#Segunda linha, todas as colunas
l_linha_1 = l[1, :]
print(l_linha_1)
print("-----------")
#Terceira linha, todas as colunas
l_linha_1 = l[2, :]
print(l_linha_1)
print("-----------")
#Todas as linha, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("-----------")
#Todas as linha, segunda coluna
l_coluna_1 = l[:, 1]
print(l_coluna_1)
print("-----------")

[[4 5]
 [6 1]
 [7 4]]
-----------
[4 5]
-----------
[6 1]
-----------
[7 4]
-----------
[4 6 7]
-----------
[5 1 4]
-----------


In [80]:
#Adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)
print("-----------")
res2 = n*o
print(res2)
print("-----------")
p = np.array([[1,2], [3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)

[[2 3]
 [4 5]]
-----------
[[1 2]
 [3 4]]
-----------
[[3 3]
 [5 5]
 [7 7]]


In [82]:
#Transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3, 5))
#Mostra a matriz transposta entre linha e coluna
print(f)
print("-----------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [85]:
#Outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3, 5))
print(r)
print("------------")
#Rearranja um conjunto de 15 elementos
#Mostra a matriz transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [88]:
#EXPRESSÕES LOGICAS
#usando where
# Cria matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
# Criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
# Criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[-0.20115349 -0.15007749  0.37053711 -0.04238733]
 [ 0.03038298 -0.21812753 -0.35503064 -1.28407137]
 [-1.48534249 -0.54176567 -0.28316339 -1.51948836]
 [ 0.16828814 -0.70926313  1.254706   -0.94135857]]
[[False False  True False]
 [ True False False False]
 [False False False False]
 [ True False  True False]]
[[-1 -1  1 -1]
 [ 1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 1 -1  1 -1]]
